# 1
name : Run Tests

# 2
on:
    push

# 3
jobs:
    build:
        runs-on: macos-l3
        # 4
        steps:
        - uses: actions/checkout@v2
        - name: Do Tests
          run: swift test
    

